### ISSUE TITLE
[BUG] AdvisoryThreatActorWithExternalObjects struct missing the Country field

### ISSUE THREAD

**Issue by peter-kwan** [vulncheck-oss/sdk-go#13]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

The `AdvisoryThreatActorWithExternalObjects` struct does not define the `"country"` field at the top level. It is a field that exists in some of the records in the `threat-actors` index.

For example, 
```
-
redacted
-
```

### Expected Behavior

I expect the struct to have this field:

```
Country *string `json:"country,omitempty"`
```

**Comment by tcampbPPU** [comment]
This issue should now be resolved with our latest release https://github.com/vulncheck-oss/sdk-go/releases/tag/v1.6.9
Thank you for taking the time to report the issue, much appreciated!

**Comment by peter-kwan** [comment]
@tcampbPPU -- Appreciate how fast you are. Thanks!
